CREATE DATABASE SKYPROTON;

USE SKYPROTON;

CREATE TABLE USER(
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATETIME DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TEACHER(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(255) NOT NULL,
    RECORDTIME DATE NOT NULL,
    PRIMARY KEY (ID)
);
